import { Typography } from '@mui/material';
import Head from 'next/head';
import Link from 'next/Link'


export default function Home() {
  return (
    <div>
      <Head>
        <title>Online Shop</title>
        <meta name="description" content="Generated by Mehdi Momenpoor" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Typography component='h1' align='center'>please change in the url ... </Typography>

      <Link href='/products/1'>
        <a> go to first product</a>
      </Link>
    </div>
  )
}
