import Head from 'next/head';


export default function Home() {
  return (
    <div>
      <Head>
        <title>Online Shop</title>
        <meta name="description" content="Generated by Mehdi Momenpoor" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <h1>please change in the url ... </h1>
    </div>
  )
}
